py39 installed: apipkg==1.5,attrs==20.3.0,cocotb==1.5.1,cocotb-bus==0.1.1,cocotb-test==0.2.0,cocotbext-axi==0.1.10,execnet==1.8.0,iniconfig==1.1.1,packaging==20.9,pluggy==0.13.1,py==1.10.0,pyparsing==2.4.7,pytest==6.2.2,pytest-forked==1.3.0,pytest-split==0.1.5,pytest-sugar==0.9.4,pytest-xdist==2.2.1,termcolor==1.1.0,toml==0.10.2
py39 run-test-pre: PYTHONHASHSEED='2686992603'
py39 run-test: commands[0] | pytest -n auto -k 'test_max_data[coffee]'
ERROR: got KeyboardInterrupt signal
============================= test session starts ==============================
platform darwin -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py39/.pytest_cache
rootdir: /Users/aignacio/projects/ravenoc, configfile: tox.ini, testpaths: tb
plugins: sugar-0.9.4, cocotb-test-0.2.0, xdist-2.2.1, split-0.1.5, forked-1.3.0
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I
gw0 [1] / gw1 [1] / gw2 [1] / gw3 [1] / gw4 [1] / gw5 [1] / gw6 [1] / gw7 [1]

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py:316: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
Traceback (most recent call last):
  File "/Users/aignacio/projects/ravenoc/.tox/py39/bin/pytest", line 8, in <module>
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/_pytest/main.py", line 304, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/_pytest/terminal.py", line 803, in pytest_sessionfinish
    outcome.get_result()
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/xdist/dsession.py", line 86, in pytest_sessionfinish
    nm.teardown_nodes()
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/xdist/workermanage.py", line 78, in teardown_nodes
    self.group.terminate(self.EXIT_TIMEOUT)
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/execnet/multi.py", line 215, in terminate
    safe_terminate(
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/execnet/multi.py", line 311, in safe_terminate
    reply.get()
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/execnet/gateway_base.py", line 206, in get
    self.waitfinish(timeout)
  File "/Users/aignacio/projects/ravenoc/.tox/py39/lib/python3.9/site-packages/execnet/gateway_base.py", line 213, in waitfinish
    if not self._result_ready.wait(timeout):
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
___________________________________ summary ____________________________________
ERROR:   py39: keyboardinterrupt
